########### Image file ###########
FROM python:3.8.11-buster
##################################

########### update and install packages ###########
# add "-y" to get rid of error
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y vim git && \
    rm -rf /var/lib/apt/lists*
###################################################

########### create workspace ###########
RUN mkdir /code
WORKDIR /code
ADD ./requirements.txt /code/
########################################

########### install packages via pip ###########
RUN pip3 install -r requirements.txt
ADD . /code/
################################################